providers = ["node"]
buildImage = "ghcr.io/railwayapp/nixpacks:ubuntu-1736208272"

[variables]
CI = "true"
NIXPACKS_METADATA = "node"
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]
cacheDirectories = [".next/cache", "node_modules/.cache"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci"]
cacheDirectories = ["/root/.npm"]
paths = ["/app/node_modules/.bin"]

[phases.setup]
nixPkgs = ["nodejs_22", "python311Full", "gnumake", "gcc", "binutils", "pkg-config"]
nixLibs = ["libuuid", "libGL"]
nixOverlays = [
  "https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz",
]

[phases.setup.env]
PYTHON = "python3"

[start]
cmd = "npm run start"
